//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts", ClrNamespace="Amor.DCFT.DES.Domain.Entities.DataContracts")]

namespace Amor.DCFT.DES.Domain.Entities.DataContracts
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataContractBase", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetDescriptor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.PublishDataSetVersionProperties))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.QueryProperties))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.FilterProperties))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.SortProperties))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetVersionDescriptor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.ReleaseDataSetVersionProperties))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.FileProperties))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.Publish.ExternalFileProperties))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.DiscoverDataSetVersionsCriteria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.DiscoverQueriesCriteria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.QueryDescriptor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.FilterDescriptor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.SortDescriptor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.DiscoverFilesCriteria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.SortValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.FileDescriptor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.QueryExecution))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.FilterValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.QueryResults))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.FileData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetSync))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetDataInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetSchemaInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Amor.DCFT.DES.Domain.Entities.DataContracts.CreateDataSetProperties))]
    public partial class DataContractBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSetDescriptor", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class DataSetDescriptor : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string CodeField;
        
        private string CollectionIdField;
        
        private string DataProviderIdField;
        
        private string DatabaseNameField;
        
        private string DescriptionField;
        
        private System.Nullable<System.Guid> IdField;
        
        private string NameField;
        
        private System.Nullable<System.TimeSpan> RetentionDurationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionId
        {
            get
            {
                return this.CollectionIdField;
            }
            set
            {
                this.CollectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataProviderId
        {
            get
            {
                return this.DataProviderIdField;
            }
            set
            {
                this.DataProviderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatabaseName
        {
            get
            {
                return this.DatabaseNameField;
            }
            set
            {
                this.DatabaseNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> RetentionDuration
        {
            get
            {
                return this.RetentionDurationField;
            }
            set
            {
                this.RetentionDurationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublishDataSetVersionProperties", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class PublishDataSetVersionProperties : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private System.Nullable<System.Guid> DataSetIdField;
        
        private System.Nullable<bool> IsMandatoryField;
        
        private Amor.DCFT.DES.Domain.Entities.DataContracts.QueryProperties[] QueriesField;
        
        private string ReasonForVersionField;
        
        private System.Nullable<bool> ReplacePreviousVersionsField;
        
        private string[] RolesField;
        
        private System.Nullable<System.Guid> SubmissionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> DataSetId
        {
            get
            {
                return this.DataSetIdField;
            }
            set
            {
                this.DataSetIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsMandatory
        {
            get
            {
                return this.IsMandatoryField;
            }
            set
            {
                this.IsMandatoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Amor.DCFT.DES.Domain.Entities.DataContracts.QueryProperties[] Queries
        {
            get
            {
                return this.QueriesField;
            }
            set
            {
                this.QueriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonForVersion
        {
            get
            {
                return this.ReasonForVersionField;
            }
            set
            {
                this.ReasonForVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ReplacePreviousVersions
        {
            get
            {
                return this.ReplacePreviousVersionsField;
            }
            set
            {
                this.ReplacePreviousVersionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> SubmissionId
        {
            get
            {
                return this.SubmissionIdField;
            }
            set
            {
                this.SubmissionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryProperties", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class QueryProperties : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string CodeField;
        
        private string DescriptionField;
        
        private Amor.DCFT.DES.Domain.Entities.DataContracts.FilterProperties[] FilterPropertiesField;
        
        private System.Nullable<bool> GetTotalCountSupportedField;
        
        private string NameField;
        
        private System.Nullable<bool> PagingSupportedField;
        
        private string[] RolesField;
        
        private Amor.DCFT.DES.Domain.Entities.DataContracts.SortProperties[] SortPropertiesField;
        
        private string StoredProcedureNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Amor.DCFT.DES.Domain.Entities.DataContracts.FilterProperties[] FilterProperties
        {
            get
            {
                return this.FilterPropertiesField;
            }
            set
            {
                this.FilterPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> GetTotalCountSupported
        {
            get
            {
                return this.GetTotalCountSupportedField;
            }
            set
            {
                this.GetTotalCountSupportedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> PagingSupported
        {
            get
            {
                return this.PagingSupportedField;
            }
            set
            {
                this.PagingSupportedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Amor.DCFT.DES.Domain.Entities.DataContracts.SortProperties[] SortProperties
        {
            get
            {
                return this.SortPropertiesField;
            }
            set
            {
                this.SortPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoredProcedureName
        {
            get
            {
                return this.StoredProcedureNameField;
            }
            set
            {
                this.StoredProcedureNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterProperties", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class FilterProperties : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string FieldDescriptionField;
        
        private string FieldNameField;
        
        private string FieldOperatorField;
        
        private string FieldTypeField;
        
        private System.Nullable<bool> IsRequiredField;
        
        private string[] PickListValuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldDescription
        {
            get
            {
                return this.FieldDescriptionField;
            }
            set
            {
                this.FieldDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName
        {
            get
            {
                return this.FieldNameField;
            }
            set
            {
                this.FieldNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldOperator
        {
            get
            {
                return this.FieldOperatorField;
            }
            set
            {
                this.FieldOperatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldType
        {
            get
            {
                return this.FieldTypeField;
            }
            set
            {
                this.FieldTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsRequired
        {
            get
            {
                return this.IsRequiredField;
            }
            set
            {
                this.IsRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PickListValues
        {
            get
            {
                return this.PickListValuesField;
            }
            set
            {
                this.PickListValuesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortProperties", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class SortProperties : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string FieldDescriptionField;
        
        private string FieldNameField;
        
        private System.Nullable<bool> IsRequiredField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldDescription
        {
            get
            {
                return this.FieldDescriptionField;
            }
            set
            {
                this.FieldDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName
        {
            get
            {
                return this.FieldNameField;
            }
            set
            {
                this.FieldNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsRequired
        {
            get
            {
                return this.IsRequiredField;
            }
            set
            {
                this.IsRequiredField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSetVersionDescriptor", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class DataSetVersionDescriptor : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private System.Nullable<System.Guid> DataSetIdField;
        
        private string DatabaseNameField;
        
        private System.Nullable<bool> HasBeenThroughQualityAssuranceField;
        
        private System.Nullable<System.Guid> IdField;
        
        private System.Nullable<bool> IsMandatoryField;
        
        private System.Nullable<System.DateTime> PublishedDateTimeField;
        
        private System.Nullable<Amor.DCFT.DES.Domain.Entities.DataContracts.PublishedStateDescriptor> PublishedStateField;
        
        private string ReasonForVersionField;
        
        private string[] RolesField;
        
        private System.Nullable<int> VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> DataSetId
        {
            get
            {
                return this.DataSetIdField;
            }
            set
            {
                this.DataSetIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatabaseName
        {
            get
            {
                return this.DatabaseNameField;
            }
            set
            {
                this.DatabaseNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> HasBeenThroughQualityAssurance
        {
            get
            {
                return this.HasBeenThroughQualityAssuranceField;
            }
            set
            {
                this.HasBeenThroughQualityAssuranceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsMandatory
        {
            get
            {
                return this.IsMandatoryField;
            }
            set
            {
                this.IsMandatoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PublishedDateTime
        {
            get
            {
                return this.PublishedDateTimeField;
            }
            set
            {
                this.PublishedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Amor.DCFT.DES.Domain.Entities.DataContracts.PublishedStateDescriptor> PublishedState
        {
            get
            {
                return this.PublishedStateField;
            }
            set
            {
                this.PublishedStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonForVersion
        {
            get
            {
                return this.ReasonForVersionField;
            }
            set
            {
                this.ReasonForVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReleaseDataSetVersionProperties", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class ReleaseDataSetVersionProperties : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private System.Nullable<System.Guid> DataSetVersionIdField;
        
        private System.Nullable<bool> ReplacePreviousVersionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> DataSetVersionId
        {
            get
            {
                return this.DataSetVersionIdField;
            }
            set
            {
                this.DataSetVersionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ReplacePreviousVersions
        {
            get
            {
                return this.ReplacePreviousVersionsField;
            }
            set
            {
                this.ReplacePreviousVersionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileProperties", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class FileProperties : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string CollectionIdField;
        
        private string DataProviderIdField;
        
        private string DescriptionField;
        
        private string DispositionNameField;
        
        private string EventTypeField;
        
        private byte[] FileContentField;
        
        private string FileNameField;
        
        private System.Nullable<long> FileSizeBytesField;
        
        private string FileTypeField;
        
        private System.Nullable<bool> IsMonitoredField;
        
        private string MimeTypeField;
        
        private string ReportTypeField;
        
        private System.Nullable<System.TimeSpan> RetentionDurationField;
        
        private string[] RolesField;
        
        private string ScreenNameField;
        
        private System.Nullable<System.Guid> SubmissionIdField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionId
        {
            get
            {
                return this.CollectionIdField;
            }
            set
            {
                this.CollectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataProviderId
        {
            get
            {
                return this.DataProviderIdField;
            }
            set
            {
                this.DataProviderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DispositionName
        {
            get
            {
                return this.DispositionNameField;
            }
            set
            {
                this.DispositionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventType
        {
            get
            {
                return this.EventTypeField;
            }
            set
            {
                this.EventTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileContent
        {
            get
            {
                return this.FileContentField;
            }
            set
            {
                this.FileContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FileSizeBytes
        {
            get
            {
                return this.FileSizeBytesField;
            }
            set
            {
                this.FileSizeBytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsMonitored
        {
            get
            {
                return this.IsMonitoredField;
            }
            set
            {
                this.IsMonitoredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MimeType
        {
            get
            {
                return this.MimeTypeField;
            }
            set
            {
                this.MimeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportType
        {
            get
            {
                return this.ReportTypeField;
            }
            set
            {
                this.ReportTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> RetentionDuration
        {
            get
            {
                return this.RetentionDurationField;
            }
            set
            {
                this.RetentionDurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScreenName
        {
            get
            {
                return this.ScreenNameField;
            }
            set
            {
                this.ScreenNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> SubmissionId
        {
            get
            {
                return this.SubmissionIdField;
            }
            set
            {
                this.SubmissionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiscoverDataSetVersionsCriteria", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class DiscoverDataSetVersionsCriteria : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string DataSetCollectionIdField;
        
        private string DataSetDataProviderIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataSetCollectionId
        {
            get
            {
                return this.DataSetCollectionIdField;
            }
            set
            {
                this.DataSetCollectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataSetDataProviderId
        {
            get
            {
                return this.DataSetDataProviderIdField;
            }
            set
            {
                this.DataSetDataProviderIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiscoverQueriesCriteria", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class DiscoverQueriesCriteria : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private System.Nullable<System.Guid> DataSetVersionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> DataSetVersionId
        {
            get
            {
                return this.DataSetVersionIdField;
            }
            set
            {
                this.DataSetVersionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryDescriptor", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class QueryDescriptor : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string CodeField;
        
        private string DescriptionField;
        
        private Amor.DCFT.DES.Domain.Entities.DataContracts.FilterDescriptor[] FilterDescriptorsField;
        
        private System.Nullable<bool> GetTotalCountSupportedField;
        
        private System.Nullable<System.Guid> IdField;
        
        private string NameField;
        
        private System.Nullable<bool> PagingSupportedField;
        
        private string[] RolesField;
        
        private Amor.DCFT.DES.Domain.Entities.DataContracts.SortDescriptor[] SortDescriptorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Amor.DCFT.DES.Domain.Entities.DataContracts.FilterDescriptor[] FilterDescriptors
        {
            get
            {
                return this.FilterDescriptorsField;
            }
            set
            {
                this.FilterDescriptorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> GetTotalCountSupported
        {
            get
            {
                return this.GetTotalCountSupportedField;
            }
            set
            {
                this.GetTotalCountSupportedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> PagingSupported
        {
            get
            {
                return this.PagingSupportedField;
            }
            set
            {
                this.PagingSupportedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Amor.DCFT.DES.Domain.Entities.DataContracts.SortDescriptor[] SortDescriptors
        {
            get
            {
                return this.SortDescriptorsField;
            }
            set
            {
                this.SortDescriptorsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterDescriptor", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class FilterDescriptor : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string FieldDescriptionField;
        
        private string FieldNameField;
        
        private string FieldOperatorField;
        
        private string FieldTypeField;
        
        private System.Nullable<bool> IsRequiredField;
        
        private string[] PickListValuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldDescription
        {
            get
            {
                return this.FieldDescriptionField;
            }
            set
            {
                this.FieldDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName
        {
            get
            {
                return this.FieldNameField;
            }
            set
            {
                this.FieldNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldOperator
        {
            get
            {
                return this.FieldOperatorField;
            }
            set
            {
                this.FieldOperatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldType
        {
            get
            {
                return this.FieldTypeField;
            }
            set
            {
                this.FieldTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsRequired
        {
            get
            {
                return this.IsRequiredField;
            }
            set
            {
                this.IsRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PickListValues
        {
            get
            {
                return this.PickListValuesField;
            }
            set
            {
                this.PickListValuesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortDescriptor", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class SortDescriptor : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string FieldDescriptionField;
        
        private string FieldNameField;
        
        private System.Nullable<bool> IsRequiredField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldDescription
        {
            get
            {
                return this.FieldDescriptionField;
            }
            set
            {
                this.FieldDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName
        {
            get
            {
                return this.FieldNameField;
            }
            set
            {
                this.FieldNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsRequired
        {
            get
            {
                return this.IsRequiredField;
            }
            set
            {
                this.IsRequiredField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiscoverFilesCriteria", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class DiscoverFilesCriteria : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string CollectionIdField;
        
        private string DataProviderIdField;
        
        private string FileTypeField;
        
        private System.Nullable<int> PageNumberField;
        
        private System.Nullable<int> PageSizeField;
        
        private string[] RolesField;
        
        private Amor.DCFT.DES.Domain.Entities.DataContracts.SortValue[] SortValuesField;
        
        private System.Nullable<System.Guid> SubmissionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionId
        {
            get
            {
                return this.CollectionIdField;
            }
            set
            {
                this.CollectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataProviderId
        {
            get
            {
                return this.DataProviderIdField;
            }
            set
            {
                this.DataProviderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Amor.DCFT.DES.Domain.Entities.DataContracts.SortValue[] SortValues
        {
            get
            {
                return this.SortValuesField;
            }
            set
            {
                this.SortValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> SubmissionId
        {
            get
            {
                return this.SubmissionIdField;
            }
            set
            {
                this.SubmissionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortValue", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class SortValue : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string FieldNameField;
        
        private System.Nullable<Amor.DCFT.DES.Domain.Entities.DataContracts.SortOrder> SortOrderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName
        {
            get
            {
                return this.FieldNameField;
            }
            set
            {
                this.FieldNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Amor.DCFT.DES.Domain.Entities.DataContracts.SortOrder> SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                this.SortOrderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileDescriptor", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class FileDescriptor : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string CollectionIdField;
        
        private string DataProviderIdField;
        
        private string DescriptionField;
        
        private string FileNameField;
        
        private System.Nullable<long> FileSizeBytesField;
        
        private string FileTypeField;
        
        private System.Nullable<System.Guid> IdField;
        
        private string MimeTypeField;
        
        private System.Nullable<System.DateTime> PublishedDateTimeField;
        
        private System.Nullable<System.TimeSpan> RetentionDurationField;
        
        private string[] RolesField;
        
        private System.Nullable<System.Guid> SubmissionIdField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionId
        {
            get
            {
                return this.CollectionIdField;
            }
            set
            {
                this.CollectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataProviderId
        {
            get
            {
                return this.DataProviderIdField;
            }
            set
            {
                this.DataProviderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FileSizeBytes
        {
            get
            {
                return this.FileSizeBytesField;
            }
            set
            {
                this.FileSizeBytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MimeType
        {
            get
            {
                return this.MimeTypeField;
            }
            set
            {
                this.MimeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PublishedDateTime
        {
            get
            {
                return this.PublishedDateTimeField;
            }
            set
            {
                this.PublishedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> RetentionDuration
        {
            get
            {
                return this.RetentionDurationField;
            }
            set
            {
                this.RetentionDurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> SubmissionId
        {
            get
            {
                return this.SubmissionIdField;
            }
            set
            {
                this.SubmissionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryExecution", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class QueryExecution : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private Amor.DCFT.DES.Domain.Entities.DataContracts.FilterValue[] FilterValuesField;
        
        private System.Nullable<int> PageNumberField;
        
        private System.Nullable<int> PageSizeField;
        
        private Amor.DCFT.DES.Domain.Entities.DataContracts.SortValue[] SortValuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Amor.DCFT.DES.Domain.Entities.DataContracts.FilterValue[] FilterValues
        {
            get
            {
                return this.FilterValuesField;
            }
            set
            {
                this.FilterValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Amor.DCFT.DES.Domain.Entities.DataContracts.SortValue[] SortValues
        {
            get
            {
                return this.SortValuesField;
            }
            set
            {
                this.SortValuesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterValue", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class FilterValue : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string FieldNameField;
        
        private string FieldValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName
        {
            get
            {
                return this.FieldNameField;
            }
            set
            {
                this.FieldNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldValue
        {
            get
            {
                return this.FieldValueField;
            }
            set
            {
                this.FieldValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResults", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class QueryResults : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string[] FieldNamesField;
        
        private string[][] ResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] FieldNames
        {
            get
            {
                return this.FieldNamesField;
            }
            set
            {
                this.FieldNamesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] Results
        {
            get
            {
                return this.ResultsField;
            }
            set
            {
                this.ResultsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileData", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class FileData : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string CollectionIdField;
        
        private string DataProviderIdField;
        
        private string DescriptionField;
        
        private byte[] FileContentField;
        
        private string FileNameField;
        
        private System.Nullable<long> FileSizeBytesField;
        
        private string FileTypeField;
        
        private System.Nullable<System.Guid> IdField;
        
        private string MimeTypeField;
        
        private System.Nullable<System.DateTime> PublishedDateTimeField;
        
        private string[] RolesField;
        
        private System.Nullable<System.Guid> SubmissionIdField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionId
        {
            get
            {
                return this.CollectionIdField;
            }
            set
            {
                this.CollectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataProviderId
        {
            get
            {
                return this.DataProviderIdField;
            }
            set
            {
                this.DataProviderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileContent
        {
            get
            {
                return this.FileContentField;
            }
            set
            {
                this.FileContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FileSizeBytes
        {
            get
            {
                return this.FileSizeBytesField;
            }
            set
            {
                this.FileSizeBytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MimeType
        {
            get
            {
                return this.MimeTypeField;
            }
            set
            {
                this.MimeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PublishedDateTime
        {
            get
            {
                return this.PublishedDateTimeField;
            }
            set
            {
                this.PublishedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> SubmissionId
        {
            get
            {
                return this.SubmissionIdField;
            }
            set
            {
                this.SubmissionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSetSync", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class DataSetSync : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetDataInfo[] DataSetDataInfosField;
        
        private Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetSchemaInfo DataSetSchemaInfoField;
        
        private System.Nullable<bool> SchemaChangedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetDataInfo[] DataSetDataInfos
        {
            get
            {
                return this.DataSetDataInfosField;
            }
            set
            {
                this.DataSetDataInfosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetSchemaInfo DataSetSchemaInfo
        {
            get
            {
                return this.DataSetSchemaInfoField;
            }
            set
            {
                this.DataSetSchemaInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SchemaChanged
        {
            get
            {
                return this.SchemaChangedField;
            }
            set
            {
                this.SchemaChangedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSetDataInfo", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class DataSetDataInfo : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private byte[][] DataSetDataScriptField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[][] DataSetDataScript
        {
            get
            {
                return this.DataSetDataScriptField;
            }
            set
            {
                this.DataSetDataScriptField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSetSchemaInfo", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class DataSetSchemaInfo : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private byte[][] DataSetSchemaScriptsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[][] DataSetSchemaScripts
        {
            get
            {
                return this.DataSetSchemaScriptsField;
            }
            set
            {
                this.DataSetSchemaScriptsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateDataSetProperties", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public partial class CreateDataSetProperties : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string CodeField;
        
        private string CollectionIdField;
        
        private string DataProviderIdField;
        
        private string DescriptionField;
        
        private string NameField;
        
        private System.Nullable<System.TimeSpan> RetentionDurationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionId
        {
            get
            {
                return this.CollectionIdField;
            }
            set
            {
                this.CollectionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataProviderId
        {
            get
            {
                return this.DataProviderIdField;
            }
            set
            {
                this.DataProviderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> RetentionDuration
        {
            get
            {
                return this.RetentionDurationField;
            }
            set
            {
                this.RetentionDurationField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublishedStateDescriptor", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public enum PublishedStateDescriptor : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingQualityAssurance = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Published = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortOrder", Namespace="http://ws.imservices.org.uk/dcft/deds/1.0/datacontracts")]
    public enum SortOrder : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ascending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Descending = 1,
    }
}
namespace Amor.DCFT.DES.Domain.Entities.DataContracts.Publish
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExternalFileProperties", Namespace="http://schemas.datacontract.org/2004/07/Amor.DCFT.DES.Domain.Entities.DataContrac" +
        "ts.Publish")]
    public partial class ExternalFileProperties : Amor.DCFT.DES.Domain.Entities.DataContracts.DataContractBase
    {
        
        private string CollectionField;
        
        private string DataProviderIdField;
        
        private string DescriptionField;
        
        private byte[] FileContentField;
        
        private string FileNameField;
        
        private System.Nullable<long> FileSizeBytesField;
        
        private string FileTypeField;
        
        private string MimeTypeField;
        
        private string ReportTypeField;
        
        private string[] RolesField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collection
        {
            get
            {
                return this.CollectionField;
            }
            set
            {
                this.CollectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataProviderId
        {
            get
            {
                return this.DataProviderIdField;
            }
            set
            {
                this.DataProviderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileContent
        {
            get
            {
                return this.FileContentField;
            }
            set
            {
                this.FileContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FileSizeBytes
        {
            get
            {
                return this.FileSizeBytesField;
            }
            set
            {
                this.FileSizeBytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MimeType
        {
            get
            {
                return this.MimeTypeField;
            }
            set
            {
                this.MimeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportType
        {
            get
            {
                return this.ReportTypeField;
            }
            set
            {
                this.ReportTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.imservices.org.uk/dcft/deds/1.0", ConfigurationName="IDedsPublishService")]
public interface IDedsPublishService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/CreateDataSet", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/CreateDataSetRespon" +
        "se")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetDescriptor CreateDataSet(Amor.DCFT.DES.Domain.Entities.DataContracts.CreateDataSetProperties createDataSetProperties);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/SubmitDataSetVersio" +
        "nForQualityAssurance", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/SubmitDataSetVersio" +
        "nForQualityAssuranceResponse")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetVersionDescriptor SubmitDataSetVersionForQualityAssurance(Amor.DCFT.DES.Domain.Entities.DataContracts.PublishDataSetVersionProperties publishDataSetVersionProperties);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/ReleaseDataSetVersi" +
        "onFromQualityAssurance", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/ReleaseDataSetVersi" +
        "onFromQualityAssuranceResponse")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetVersionDescriptor ReleaseDataSetVersionFromQualityAssurance(Amor.DCFT.DES.Domain.Entities.DataContracts.ReleaseDataSetVersionProperties releaseDataSetVersionProperties);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/PublishDataSetVersi" +
        "on", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/PublishDataSetVersi" +
        "onResponse")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetVersionDescriptor PublishDataSetVersion(Amor.DCFT.DES.Domain.Entities.DataContracts.PublishDataSetVersionProperties publishDataSetVersionProperties);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/PublishFile", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/PublishFileResponse" +
        "")]
    System.Guid PublishFile(Amor.DCFT.DES.Domain.Entities.DataContracts.FileProperties fileProperties);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/PublishExternalFile" +
        "", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/PublishExternalFile" +
        "Response")]
    System.Guid PublishExternalFile(Amor.DCFT.DES.Domain.Entities.DataContracts.Publish.ExternalFileProperties externalFileProperties);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/DeleteDataSetVersio" +
        "n", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/DeleteDataSetVersio" +
        "nResponse")]
    void DeleteDataSetVersion(System.Guid dataSetVersionId, string reasonForDeletion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/DeleteDataSet", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/DeleteDataSetRespon" +
        "se")]
    void DeleteDataSet(string code, string reasonForDeletion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/DeleteFile", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/DeleteFileResponse")]
    void DeleteFile(System.Guid fileId, string reasonForDeletion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/DeleteFileBatch", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsPublishService/DeleteFileBatchResp" +
        "onse")]
    System.Guid[] DeleteFileBatch(System.Guid[] fileIds, string reasonForDeletion);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDedsPublishServiceChannel : IDedsPublishService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DedsPublishServiceClient : System.ServiceModel.ClientBase<IDedsPublishService>, IDedsPublishService
{
    
    public DedsPublishServiceClient()
    {
    }
    
    public DedsPublishServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DedsPublishServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DedsPublishServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DedsPublishServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetDescriptor CreateDataSet(Amor.DCFT.DES.Domain.Entities.DataContracts.CreateDataSetProperties createDataSetProperties)
    {
        return base.Channel.CreateDataSet(createDataSetProperties);
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetVersionDescriptor SubmitDataSetVersionForQualityAssurance(Amor.DCFT.DES.Domain.Entities.DataContracts.PublishDataSetVersionProperties publishDataSetVersionProperties)
    {
        return base.Channel.SubmitDataSetVersionForQualityAssurance(publishDataSetVersionProperties);
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetVersionDescriptor ReleaseDataSetVersionFromQualityAssurance(Amor.DCFT.DES.Domain.Entities.DataContracts.ReleaseDataSetVersionProperties releaseDataSetVersionProperties)
    {
        return base.Channel.ReleaseDataSetVersionFromQualityAssurance(releaseDataSetVersionProperties);
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetVersionDescriptor PublishDataSetVersion(Amor.DCFT.DES.Domain.Entities.DataContracts.PublishDataSetVersionProperties publishDataSetVersionProperties)
    {
        return base.Channel.PublishDataSetVersion(publishDataSetVersionProperties);
    }
    
    public System.Guid PublishFile(Amor.DCFT.DES.Domain.Entities.DataContracts.FileProperties fileProperties)
    {
        return base.Channel.PublishFile(fileProperties);
    }
    
    public System.Guid PublishExternalFile(Amor.DCFT.DES.Domain.Entities.DataContracts.Publish.ExternalFileProperties externalFileProperties)
    {
        return base.Channel.PublishExternalFile(externalFileProperties);
    }
    
    public void DeleteDataSetVersion(System.Guid dataSetVersionId, string reasonForDeletion)
    {
        base.Channel.DeleteDataSetVersion(dataSetVersionId, reasonForDeletion);
    }
    
    public void DeleteDataSet(string code, string reasonForDeletion)
    {
        base.Channel.DeleteDataSet(code, reasonForDeletion);
    }
    
    public void DeleteFile(System.Guid fileId, string reasonForDeletion)
    {
        base.Channel.DeleteFile(fileId, reasonForDeletion);
    }
    
    public System.Guid[] DeleteFileBatch(System.Guid[] fileIds, string reasonForDeletion)
    {
        return base.Channel.DeleteFileBatch(fileIds, reasonForDeletion);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.imservices.org.uk/dcft/deds/1.0", ConfigurationName="IDedsSearchService")]
public interface IDedsSearchService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/GetDataSet", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/GetDataSetResponse")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetDescriptor GetDataSet(System.Guid dataSetId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/GetDataSetByCode", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/GetDataSetByCodeResp" +
        "onse")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetDescriptor GetDataSetByCode(string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/DiscoverDataSetVersi" +
        "ons", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/DiscoverDataSetVersi" +
        "onsResponse")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetVersionDescriptor[] DiscoverDataSetVersions(Amor.DCFT.DES.Domain.Entities.DataContracts.DiscoverDataSetVersionsCriteria discoverDataSetVersionsCriteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/DiscoverQueries", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/DiscoverQueriesRespo" +
        "nse")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.QueryDescriptor[] DiscoverQueries(Amor.DCFT.DES.Domain.Entities.DataContracts.DiscoverQueriesCriteria discoverQueriesCriteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/DiscoverFiles", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/DiscoverFilesRespons" +
        "e")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.FileDescriptor[] DiscoverFiles(Amor.DCFT.DES.Domain.Entities.DataContracts.DiscoverFilesCriteria discoverFilesCriteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/DiscoverFilesCount", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/DiscoverFilesCountRe" +
        "sponse")]
    long DiscoverFilesCount(Amor.DCFT.DES.Domain.Entities.DataContracts.DiscoverFilesCriteria discoverFilesCriteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/ExecuteQuery", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/ExecuteQueryResponse" +
        "")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.QueryResults[] ExecuteQuery(System.Guid queryId, Amor.DCFT.DES.Domain.Entities.DataContracts.QueryExecution queryExecution);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/GetTotalCount", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/GetTotalCountRespons" +
        "e")]
    long GetTotalCount(System.Guid queryId, Amor.DCFT.DES.Domain.Entities.DataContracts.QueryExecution queryExecution);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/ExecuteQueryByCode", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/ExecuteQueryByCodeRe" +
        "sponse")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.QueryResults[] ExecuteQueryByCode(System.Guid dataSetVersionId, string queryCode, Amor.DCFT.DES.Domain.Entities.DataContracts.QueryExecution queryExecution);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/GetTotalCountByCode", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/GetTotalCountByCodeR" +
        "esponse")]
    long GetTotalCountByCode(System.Guid dataSetVersionId, string queryCode, Amor.DCFT.DES.Domain.Entities.DataContracts.QueryExecution queryExecution);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/GetFile", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/GetFileResponse")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.FileData GetFile(System.Guid fileId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/GetLatestPublishedDa" +
        "taSetVersion", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/GetLatestPublishedDa" +
        "taSetVersionResponse")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetVersionDescriptor GetLatestPublishedDataSetVersion(string dataSetCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/GetPublishedDataSetV" +
        "ersions", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsSearchService/GetPublishedDataSetV" +
        "ersionsResponse")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetVersionDescriptor[] GetPublishedDataSetVersions(string dataSetCode);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDedsSearchServiceChannel : IDedsSearchService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DedsSearchServiceClient : System.ServiceModel.ClientBase<IDedsSearchService>, IDedsSearchService
{
    
    public DedsSearchServiceClient()
    {
    }
    
    public DedsSearchServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DedsSearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DedsSearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DedsSearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetDescriptor GetDataSet(System.Guid dataSetId)
    {
        return base.Channel.GetDataSet(dataSetId);
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetDescriptor GetDataSetByCode(string code)
    {
        return base.Channel.GetDataSetByCode(code);
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetVersionDescriptor[] DiscoverDataSetVersions(Amor.DCFT.DES.Domain.Entities.DataContracts.DiscoverDataSetVersionsCriteria discoverDataSetVersionsCriteria)
    {
        return base.Channel.DiscoverDataSetVersions(discoverDataSetVersionsCriteria);
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.QueryDescriptor[] DiscoverQueries(Amor.DCFT.DES.Domain.Entities.DataContracts.DiscoverQueriesCriteria discoverQueriesCriteria)
    {
        return base.Channel.DiscoverQueries(discoverQueriesCriteria);
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.FileDescriptor[] DiscoverFiles(Amor.DCFT.DES.Domain.Entities.DataContracts.DiscoverFilesCriteria discoverFilesCriteria)
    {
        return base.Channel.DiscoverFiles(discoverFilesCriteria);
    }
    
    public long DiscoverFilesCount(Amor.DCFT.DES.Domain.Entities.DataContracts.DiscoverFilesCriteria discoverFilesCriteria)
    {
        return base.Channel.DiscoverFilesCount(discoverFilesCriteria);
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.QueryResults[] ExecuteQuery(System.Guid queryId, Amor.DCFT.DES.Domain.Entities.DataContracts.QueryExecution queryExecution)
    {
        return base.Channel.ExecuteQuery(queryId, queryExecution);
    }
    
    public long GetTotalCount(System.Guid queryId, Amor.DCFT.DES.Domain.Entities.DataContracts.QueryExecution queryExecution)
    {
        return base.Channel.GetTotalCount(queryId, queryExecution);
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.QueryResults[] ExecuteQueryByCode(System.Guid dataSetVersionId, string queryCode, Amor.DCFT.DES.Domain.Entities.DataContracts.QueryExecution queryExecution)
    {
        return base.Channel.ExecuteQueryByCode(dataSetVersionId, queryCode, queryExecution);
    }
    
    public long GetTotalCountByCode(System.Guid dataSetVersionId, string queryCode, Amor.DCFT.DES.Domain.Entities.DataContracts.QueryExecution queryExecution)
    {
        return base.Channel.GetTotalCountByCode(dataSetVersionId, queryCode, queryExecution);
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.FileData GetFile(System.Guid fileId)
    {
        return base.Channel.GetFile(fileId);
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetVersionDescriptor GetLatestPublishedDataSetVersion(string dataSetCode)
    {
        return base.Channel.GetLatestPublishedDataSetVersion(dataSetCode);
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetVersionDescriptor[] GetPublishedDataSetVersions(string dataSetCode)
    {
        return base.Channel.GetPublishedDataSetVersions(dataSetCode);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.imservices.org.uk/dcft/deds/1.0", ConfigurationName="IDedsDataSetSyncService")]
public interface IDedsDataSetSyncService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsDataSetSyncService/GetInitialDataS" +
        "etSync", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsDataSetSyncService/GetInitialDataS" +
        "etSyncResponse")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetSync GetInitialDataSetSync(System.Guid dataSetVersionId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsDataSetSyncService/GetDeltaDataSet" +
        "Sync", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsDataSetSyncService/GetDeltaDataSet" +
        "SyncResponse")]
    Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetSync GetDeltaDataSetSync(System.Guid oldDataSetVersionId, System.Guid newDataSetVersionId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDedsDataSetSyncServiceChannel : IDedsDataSetSyncService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DedsDataSetSyncServiceClient : System.ServiceModel.ClientBase<IDedsDataSetSyncService>, IDedsDataSetSyncService
{
    
    public DedsDataSetSyncServiceClient()
    {
    }
    
    public DedsDataSetSyncServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DedsDataSetSyncServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DedsDataSetSyncServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DedsDataSetSyncServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetSync GetInitialDataSetSync(System.Guid dataSetVersionId)
    {
        return base.Channel.GetInitialDataSetSync(dataSetVersionId);
    }
    
    public Amor.DCFT.DES.Domain.Entities.DataContracts.DataSetSync GetDeltaDataSetSync(System.Guid oldDataSetVersionId, System.Guid newDataSetVersionId)
    {
        return base.Channel.GetDeltaDataSetSync(oldDataSetVersionId, newDataSetVersionId);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.imservices.org.uk/dcft/deds/1.0", ConfigurationName="IDedsAdminService")]
public interface IDedsAdminService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsAdminService/SetDataSetVersionRole" +
        "s", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsAdminService/SetDataSetVersionRole" +
        "sResponse")]
    void SetDataSetVersionRoles(System.Guid dataSetVersionId, string[] roles);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsAdminService/SetQueryRoles", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsAdminService/SetQueryRolesResponse" +
        "")]
    void SetQueryRoles(System.Guid queryId, string[] roles);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsAdminService/SetFileRoles", ReplyAction="http://ws.imservices.org.uk/dcft/deds/1.0/IDedsAdminService/SetFileRolesResponse")]
    void SetFileRoles(System.Guid fileId, string[] roles);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDedsAdminServiceChannel : IDedsAdminService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DedsAdminServiceClient : System.ServiceModel.ClientBase<IDedsAdminService>, IDedsAdminService
{
    
    public DedsAdminServiceClient()
    {
    }
    
    public DedsAdminServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DedsAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DedsAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DedsAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void SetDataSetVersionRoles(System.Guid dataSetVersionId, string[] roles)
    {
        base.Channel.SetDataSetVersionRoles(dataSetVersionId, roles);
    }
    
    public void SetQueryRoles(System.Guid queryId, string[] roles)
    {
        base.Channel.SetQueryRoles(queryId, roles);
    }
    
    public void SetFileRoles(System.Guid fileId, string[] roles)
    {
        base.Channel.SetFileRoles(fileId, roles);
    }
}
